jobs:
  - job: 'Clippy'
    pool:
      vmImage: 'ubuntu-16.04'
    container: 'rust:nightly'
    steps:
      - script: rustup component add clippy
        displayName: Install Clippy
      - script: cargo clippy
        displayName: Run clippy

  - job: 'Test'
    pool:
      vmImage: 'ubuntu-16.04'
    container: 'rust:nightly'
    steps:
      - script: cargo build --all
        displayName: Cargo build
      - script: cargo test --all
        displayName: Cargo test